### PR TITLE
Prepare for 1.0

### LINKED ISSUE #11: Version 1.0?
Are we happy with this interface?

@Zegnat ?

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #11 

This package has been fairly stable for a long while.

### CODE REVIEW

**Comment by Zegnat** [comment]
Seems fine to me. It has been stable to a while now. Wondering if we want to clear the other 2 PRs before pushing 1.0?

**Comment by Zegnat** [comment]
I have just rebased #27 on the latest master. It introduces a minor parameter widening on the methods (`$post` goes from `array` to `array|null`). Would love to be able to land that before version 1.0. As I think it is the only thing (from both PRs and issues) that actually signifies a method signature change.

**Comment by Nyholm** [comment]
PR is rebased and the BC break is documented

**Comment by Nyholm** [comment]
I made another small change to this PR. What do you think?

**Comment by Zegnat** [comment]
Aah, I must have missed that one. If I read this correctly, this is to allow the user to pass in `null` when they want to specify `$files` and `$body`? Makes a lot of sense to me!

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
